sudo: false
language: node_js
node_js:
  - 12.16.2
branches:
  only:
    - develop
before_install:
- cd themes/obsidian
- npm i
- cd ../..
install:
- npm i
script:
  - npx hexo generate
deploy:
  provider: pages
  fqdn: daivasmara.com
  skip-cleanup: true
  github-token: $GH_TOKEN
  target_branch: master
  on:
    branch: develop
  local-dir: public
