sudo: false
language: node_js
node_js:
  - 12.16.2
branches:
  only:
    - develop
before_install:
- cd themes/obsidian
- npm i
- npx hexo clean
- npx hexo generate
- cd ../..
install:
- npm i
script:
  - npx hexo clean
  - npx hexo generate
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  target_branch: master
  on:
    branch: develop
  local-dir: public
