sudo: false
language: node_js
node_js:
  - 12.16.2 # use nodejs v10 LTS
branches:
  only:
    - develop # build develop branch only
before_install:
- cd themes/obsidian
- yarn
- cd ../..
install:
- yarn
script:
  - hexo generate # generate static files
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  keep-history: true
  target_branch: master
  on:
    branch: develop
  local-dir: public
